spring:
  datasource:
    url: jdbc:postgresql://172.23.26.209:5432/postgres?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

logging:
  level:
    com.training: debug
    org.springframework.web: debug


